# Generated by Django 5.2.4 on 2025-12-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20251121_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='pdf_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
