# Generated by Django 5.2.4 on 2025-12-06 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_consulta_pdf_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='pdf_path',
        ),
    ]
