# Generated by Django 5.2.4 on 2026-01-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_candidatoprofesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='intentos',
            field=models.IntegerField(default=0),
        ),
    ]
